name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-mobileApp:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Select Xcode 16.4
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Start test dependencies
        run: |
          cd server
          docker compose up -d
          docker ps

      - name: Restore solution workloads
        run: |
          cd mobileApp
          dotnet workload restore

      - name: Build & test mobile app
        run: |
          cd mobileApp
          dotnet restore
          dotnet build -c Debug
          dotnet test --no-build --verbosity normal

      - name: Stop test dependencies
        if: always()
        run: |
          cd server
          docker compose down


      - name: Notify successfull mobile app build and test
        run: |
          echo "Mobile app build and tests successfull"

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify successfull server build and test
        run: |
          echo "Server build and tests successfull"

  test-cars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify successfull cars build and test
        run: |
          echo "Cars build and tests successfull"
