name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-mobileApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Start test dependencies
        run: |
          cd server
          docker compose up -d
          docker ps

      - name: Restore solution workloads
        run: |
          cd mobileApp
          dotnet workload restore

      - name: Build & test mobile app
        run: |
          cd mobileApp
          for proj in $(find . -name '*.csproj'); do
            if grep -q '<TargetFramework>net9.0</TargetFramework>' "$proj"; then
              dotnet build "$proj" -c Debug
              dotnet test "$proj" --no-build --framework net9.0 --verbosity normal
            fi
          done

      - name: Stop test dependencies
        if: always()
        run: |
          cd server
          docker compose down

      - name: Notify successful mobile app build and test
        run: echo "Mobile app build and tests successful"

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify successfull server build and test
        run: |
          echo "Server build and tests successfull"

  test-cars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify successfull cars build and test
        run: |
          echo "Cars build and tests successfull"
